{"name": "Пользователь авторизуется с неверной почтой или паролем", "status": "passed", "steps": [{"name": "Проверяем вход с неверной почтой и паролем и получаем ошибку", "status": "passed", "parameters": [{"name": "only_create_user", "value": "{'email': 'erinwest@example.com', 'password': '#46TZSccBK', 'name': 'John Long'}"}], "start": 1723733809385, "stop": 1723733809738}], "start": 1723733809385, "stop": 1723733809739, "uuid": "fcb64d15-a771-42b2-ae9f-e52f4cef6488", "historyId": "a7aaeab875304835cb483ed92ac7df8a", "testCaseId": "a7aaeab875304835cb483ed92ac7df8a", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credetentials_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-LQ0DQPC"}, {"name": "thread", "value": "20004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}